Repository mmasias/24-25-PRG2, pull requests merged in 2025-03, with the labels that each got.

#189 reto003 Diego Martinez
  entregas/martinezDiego/Calculadora.java
Labels: Trabajado en rama inválida

#212 Carla Madero reto003
  entregas/maderoCarla/Calculadora.java
Labels: Bug

#231 Reto003
  entregas/chavezGuillermo/reto003/Calculadora.java
Labels: Trabajado en rama inválida

#238 Entrega 003
  entregas/valdesCarlos/reto003/Calculadora.java
Labels: Fuera de plazo

#239 Entrega 003 - Ismael Cobo
  entregas/coboIsmael/reto003/Calculadora.java
Labels: Fuera de plazo

#240 Entrega 003
  entregas/zablahBernardo/ejemplo.java
  entregas/zablahBernardo/reto003/Calculadora.java
Labels: Fuera de plazo

#241 Reto003 - Bienvenido Doalto
  entregas/doaltoBienvenido/reto003/Calculadora.java
Labels: Fuera de plazo

#243 calculadora - cambio nombre de la rama
  entregas/quintanaJuan/Reto-003/Calculadora.java
Labels: Fuera de plazo

#244 entrega-003
  entregas/cotareloDaniel/reto003/Calculadora.java
Labels: Fuera de plazo

#245 Entrega 003
  entregas/arellanoDiego/reto003/Calculadora.java
Labels: Fuera de plazo
